name: Build and Deploy Lambda


on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_deploy:

    # runner
    runs-on: ubuntu-latest

    steps:

      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Java JDK 11
      - name: set JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      # Build
      - name: Build Artifact
        run: |
          cd serverless
          mvn clean install
      # Install Packages
      - name: Install apt & zip
        run: sudo apt-get update && sudo apt-get install wget zip unzip -y

      # AWS CLI pre-installed in Ubuntu-Latest

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Zip Artifact
      - name: Zip Artifact
        run: |
          zip serverless.zip ./serverless/target/serverless-0.0.1-SNAPSHOT.jar
      # Upload Artifacts to S3
      - name: Upload Artifacts
        run: |
          aws s3 cp serverless.zip s3://${{ secrets.S3_BUCKET_NAME }}
      # Deploy Lambda Function
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
          --function-name "EmailNotification" \
          --s3-bucket ${{ secrets.S3_BUCKET_NAME}} \
          --s3-key serverless.zip